//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 070308ntt.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MY070308NTT_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDC_PICTURE1                    1000
#define IDC_PICTURE2                    1001
#define IDC_PICTURE3                    1002
#define IDC_PICTURE4                    1003
#define IDC_STATIC1                     1004
#define IDC_BUTTON_LOAD_AN_IMAGE        1005
#define IDC_BUTTON_TO_GRAY              1006
#define IDC_BUTTON_QUIT                 1007
#define IDC_PICTURE5                    1008
#define IDC_STATIC_SRC_IMAGE            1009
#define IDC_STATIC_GRAYSCALE            1010
#define IDC_STATIC_THRESHOLD            1011
#define IDC_PICTURE6                    1012
#define IDC_EDIT_THRESHOLD              1013
#define IDC_EDIT_THRESHOLD_MAX_VALUE    1014
#define IDC_COMBO_THRESHOLD_TYPE        1016
#define IDC_BUTTON_THRESHOLD            1017
#define IDC_PICTURE9                    1019
#define IDC_BUTTON_ERODE                1020
#define IDC_BUTTON_DILATE               1021
#define IDC_BUTTON_ERODE_DILATE         1022
#define IDC_BUTTON_DILATE_ERODE         1023
#define IDC_EDIT_ERODE_DILATION_RECTW   1024
#define IDC_EDIT_ERODE_DILATE_ITER      1025
#define IDC_EDIT_ERODE_DILATE_RECTH     1026
#define IDC_STATIC_ERODE_DILATE         1027
#define IDC_BUTTON_BOUNDARY_EXTRACT     1028
#define IDC_BUTTON_OPENCV_HOUGHLINE2    1029
#define IDC_COMBO_OPENCV_HOUGH_METHOD   1030
#define IDC_EDIT_OPENCV_HOUGH_RHO       1031
#define IDC_EDIT_OPENCV_HOUGH_THETA     1032
#define IDC_EDIT_OPENCV_HOUGH_THRESHOLD 1033
#define IDC_BUTTON_NTT_PROBABILISTIC_HOUGH 1034
#define IDC_BUTTON_CLEAR_VIEW           1035
#define IDC_BUTTON_NTT_PROGRESSIVE_PROBABILISTIC_HOUGH 1035
#define IDC_BUTTON_NTT_STANDARD_HOUGH   1036
#define IDC_BUTTON1                     1037
#define IDC_BUTTON_NTT_HOUGH_ACCURACY   1037
#define IDC_BUTTON_NTT_HOUGH_GREEN      1038
#define IDC_BUTTON_NTT_STANDARD_HOUGH_NEW 1039
#define IDC_BUTTON_NTT_PYRAMID_HOUGH    1040
#define IDC_EDIT_SHT_NEW_RHO            1041
#define IDC_EDIT_SHT_NEW_THETA          1042
#define IDC_EDIT_SHT_NEW_THRESHOLD      1043
#define IDC_BUTTON_LAST_DECISION        1044
#define IDC_EDIT_SHT_NEW_LINESMAX       1045
#define IDC_EDIT_LAST_DECISION_RHO      1046
#define IDC_EDIT_LAST_DECISION_THETA    1047
#define IDC_EDIT_LAST_DECISION_THRESHOLD 1048
#define IDC_EDIT_LAST_DECISION_LINESMAX 1049
#define IDC_BUTTON_SAVE_RESULT_IMG      1050
#define IDC_STATIC_NUM_DETECTED_LINES   1051
#define IDC_EDIT_LAST_DECISION_MAXGAP   1055
#define IDC_EDIT_LAST_DECISION_LINELEN  1057
#define IDC_EDIT_LAST_DECISION_LINEINLENGTH_FROM 1058
#define IDC_EDIT_LAST_DECISION_LINEINLENGTH_TO 1059
#define IDC_EDIT_LAST_DECISION_DECLINATION_THETAFROM 1060
#define IDC_EDIT_LAST_DECISION_DECLINATION_THETAFROM2 1062
#define IDC_EDIT_LAST_DECISION_DECLINATION_THETATO 1062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
